export const DELIVERY_AREAS = [
  "Ambattur OT",
  "Annanur",
  "Athipet",
  "Cholambedu",
  "Ganapathy Nagar",
  "Kallikuppam",
  "Kamalam Nagar",
  "Lenin Nagar",
  "Menambedu",
  "MKB Nagar",
  "Oragadam",
  "Pudur",
  "Ramapuram",
  "Sai Nagar",
  "Saraswati Nagar",
  "Saravana Nagar",
  "Sathyamoorthy Nagar",
  "Senthil Nagar",
  "Subramanya Nagar",
  "Tamarai Nagar",
  "Teachers Colony",
  "Thendral Nagar",
  "Thirumullaivoyal",
  "Tiruvenkadam Nagar",
  "Vaishnavi Nagar",
  "Venkatachalam Nagar",
  "Venkatapuram",
  "Venkateswara Nagar",
];